% compute and plot the unconditional autocorrelations of the actual data 
% and those of the endogenous varaibles generated by the model 
% 10-period horizon.
% load dynare simulation outputs
% needs acfcomp.m and autocov.m

clear; close all; clc;

load us_data;

%load dynare simulation outputs from the current directory
load NK_RES_Course_est_PI_MCMC_results_150000_draws;

%ACFs of data dy pinfobs obs 
acfy=acfcomp(dy(5:end));
acfpi=acfcomp(pinfobs(5:end));
acfr=acfcomp(robs(5:end));

%use the first 10 periods
acfy=acfy([2: 11],:);
acfpi=acfpi([2: 11],:);
acfr=acfr([2: 11],:);

%extract fields from Dynare outputs that contain the ACF estimates 
autocorr1 = [];

for i=1:options_.ar
      autocorr1 = [ autocorr1 diag(oo_.autocorr{i}) ]; 
end
    
%set 10-period horizon.
lag = (1:1:10);

%now I plot ACFs
F1=figure(1);
subplot(2,2,1)
set(F1, 'numbertitle','off')
set(F1, 'name', 'ACFs - NK Models')
plot(lag,acfy,'-.k','linewidth',2)
hold on
plot(lag,autocorr1(1,:)','-or','linewidth',1)
hold off
title('Output')


subplot(2,2,2)
plot(lag,acfpi,'-.k','linewidth',2)
hold on
plot(lag,autocorr1(2,:)','-or','linewidth',1)
hold off
title('Inflation')

subplot(2,2,3)
plot(lag,acfr,'-.k','linewidth',2)
hold on
plot(lag,autocorr1(3,:)','-or','linewidth',1)
hold off
title('Interest rate')

%define legend
legend('data','NK Model');
